format = "$directory$character"
right_format = """$git_status$git_branch$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = " [ﬦ](#cba6f7 bold)"
error_symbol = " [ﬦ](#f38ba8)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#89b4fa bg:#1e1e2e)[ $duration](fg:#1e1e2e bg:#89b4fa)[](fg:#89b4fa bg:none) "
disabled = false
style = "fg:#89b4fa bg:#1e1e2e"

[directory]
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#cba6f7 bg:#1e1e2e)[ $path](fg:#1e1e2e bg:#cba6f7)[](fg:#cba6f7 bg:none) "
style = "fg:#d9d7d6 bg:#1e1e2e"
truncation_length = 3
truncate_to_repo=true

[git_branch]
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#74c7ec bg:#1e1e2e)[ $branch](fg:#282c34 bg:#74c7ec)[](fg:#74c7ec bg:none) "
style = "fg:#d9d7d6 bg:#1e1e2e"

[git_status]
format="(fg:#1e1e2e bg:#1e1e2e)[](fg:#89dceb bg:#1e1e2e)[ $all_status](fg:#1e1e2e bg:#89dceb)[](fg:#89dceb bg:none) "
style = "fg:#d9d7d6 bg:#1e1e2e"
conflicted = "="
ahead ="${count}"
behind = "${count}"
diverged = "${ahead_count}${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[package]
disabled=true
